export interface Theme {
  id: string;
  name: string;
  primaryColor: string;
  tokens: Record<string, string>;
}

export const themes: Theme[] = [
  {
    id: 'dark',
    name: 'Dark',
    primaryColor: '#4f4f4f',
    tokens: {
      '--ui-interaction-primary': '#4f4f4f',
      '--ui-interaction-primary-hover': '#6b6b6b',
      '--ui-interaction-primary-selected': '#3a4655',
      '--ui-interaction-primary-selected-hover': '#4f4f4f',
      '--ui-interaction-primary-selected-active': '#6b6b6b',
      '--ui-interaction-success': '#6fbf8a',
      '--ui-interaction-success-hover': '#4e9e6d',
      '--ui-text-on-primary': '#ffffff',
      '--ui-text-on-primary-selected': '#ffffff',
      '--ui-text-on-success': '#ffffff',
      '--ui-text-on-secondary': '#4f4f4f',
      '--ui-text-on-tertiary': '#4f4f4f',
      '--ui-text-secondary': '#4f4f4f',
      '--ui-text-tertiary': '#6b6b6b',
      '--ui-text-placeholder': '#a8a8a8',
      '--ui-surface-primary': '#ffffff',
      '--ui-surface-secondary': '#3a4655',
      '--ui-surface-hover': '#f6f6f6',
      '--ui-border-default': '#d9d9d9',
      '--ui-border-subtle': '#eeeeee',
      '--ui-border-strong': '#a8a8a8',
      '--ui-status-success': '#6fbf8a',
      '--ui-status-warning': '#f3a73f',
      '--ui-status-info': '#1f8fe6',
      '--ui-status-danger': '#c62828',
      '--table-header-bg': '#3a4655',
      '--table-header-text': '#ffffff',
      '--table-header-border': '#3a4655',
      '--table-header-hover-bg': '#4f4f4f',
      '--table-body-bg': '#ffffff',
      '--table-row-bg': 'transparent',
      '--table-row-hover-bg': '#f6f6f6',
      '--table-row-selected-bg': '#3a4655',
      '--table-row-border': '#eeeeee',
      '--table-cell-text': '#4f4f4f',
      '--table-empty-text': '#4f4f4f',
      '--table-loading-text': '#4f4f4f',
    }
  },
  {
    id: 'green',
    name: 'Green',
    primaryColor: '#6fbf8a',
    tokens: {
      '--ui-interaction-primary': '#6fbf8a',
      '--ui-interaction-primary-hover': '#a6dcb2',
      '--ui-interaction-primary-selected': '#4e9e6d',
      '--ui-interaction-primary-selected-hover': '#6fbf8a',
      '--ui-interaction-primary-selected-active': '#4e9e6d',
      '--ui-interaction-success': '#4e9e6d',
      '--ui-interaction-success-hover': '#6fbf8a',
      '--ui-text-on-primary': '#ffffff',
      '--ui-text-on-primary-selected': '#ffffff',
      '--ui-text-on-success': '#ffffff',
      '--ui-text-on-secondary': '#6fbf8a',
      '--ui-text-on-tertiary': '#6fbf8a',
      '--ui-text-secondary': '#4f4f4f',
      '--ui-text-tertiary': '#6b6b6b',
      '--ui-text-placeholder': '#a8a8a8',
      '--ui-surface-primary': '#ffffff',
      '--ui-surface-secondary': '#4e9e6d',
      '--ui-surface-hover': '#f6f6f6',
      '--ui-border-default': '#d9d9d9',
      '--ui-border-subtle': '#eeeeee',
      '--ui-border-strong': '#a8a8a8',
      '--ui-status-success': '#6fbf8a',
      '--ui-status-warning': '#f3a73f',
      '--ui-status-info': '#1f8fe6',
      '--ui-status-danger': '#c62828',
      '--table-header-bg': '#4e9e6d',
      '--table-header-text': '#ffffff',
      '--table-header-border': '#4e9e6d',
      '--table-header-hover-bg': '#a6dcb2',
      '--table-body-bg': '#ffffff',
      '--table-row-bg': 'transparent',
      '--table-row-hover-bg': '#f6f6f6',
      '--table-row-selected-bg': '#4e9e6d',
      '--table-row-border': '#eeeeee',
      '--table-cell-text': '#4f4f4f',
      '--table-empty-text': '#4f4f4f',
      '--table-loading-text': '#4f4f4f',
    }
  },
  {
    id: 'blue',
    name: 'Blue',
    primaryColor: '#1f8fe6',
    tokens: {
      '--ui-interaction-primary': '#1f8fe6',
      '--ui-interaction-primary-hover': '#6cbcff',
      '--ui-interaction-primary-selected': '#197fd1',
      '--ui-interaction-primary-selected-hover': '#146ab3',
      '--ui-interaction-primary-selected-active': '#6cbcff',
      '--ui-interaction-success': '#6fbf8a',
      '--ui-interaction-success-hover': '#a6dcb2',
      '--ui-text-on-primary': '#ffffff',
      '--ui-text-on-primary-selected': '#ffffff',
      '--ui-text-on-success': '#ffffff',
      '--ui-text-on-secondary': '#1f8fe6',
      '--ui-text-on-tertiary': '#1f8fe6',
      '--ui-text-secondary': '#6b6b6b',
      '--ui-text-tertiary': '#a8a8a8',
      '--ui-text-placeholder': '#a8a8a8',
      '--ui-surface-primary': '#ffffff',
      '--ui-surface-secondary': '#197fd1',
      '--ui-surface-hover': '#e9f5ff',
      '--ui-border-default': '#d9d9d9',
      '--ui-border-subtle': '#eeeeee',
      '--ui-border-strong': '#a8a8a8',
      '--ui-status-success': '#6fbf8a',
      '--ui-status-warning': '#f3a73f',
      '--ui-status-info': '#1f8fe6',
      '--ui-status-danger': '#c62828',
      '--table-header-bg': '#197fd1',
      '--table-header-text': '#ffffff',
      '--table-header-border': '#197fd1',
      '--table-header-hover-bg': '#6cbcff',
      '--table-body-bg': '#ffffff',
      '--table-row-bg': 'transparent',
      '--table-row-hover-bg': '#e9f5ff',
      '--table-row-selected-bg': '#197fd1',
      '--table-row-border': '#eeeeee',
      '--table-cell-text': '#4f4f4f',
      '--table-empty-text': '#6b6b6b',
      '--table-loading-text': '#6b6b6b',
    }
  },
  {
    id: 'purple',
    name: 'Purple',
    primaryColor: '#7b61ff',
    tokens: {
      '--ui-interaction-primary': '#7b61ff',
      '--ui-interaction-primary-hover': '#6a4ff5',
      '--ui-interaction-primary-selected': '#5e44db',
      '--ui-interaction-primary-selected-hover': '#533cc4',
      '--ui-interaction-primary-selected-active': '#4934ad',
      '--ui-interaction-success': '#22c55e',
      '--ui-interaction-success-hover': '#16a34a',
      '--ui-text-on-primary': '#ffffff',
      '--ui-text-on-primary-selected': '#ffffff',
      '--ui-text-on-success': '#ffffff',
      '--ui-text-on-secondary': '#7b61ff',
      '--ui-text-on-tertiary': '#7b61ff',
      '--ui-text-secondary': '#4a5568',
      '--ui-text-tertiary': '#718096',
      '--ui-text-placeholder': '#a0aec0',
      '--ui-surface-primary': '#ffffff',
      '--ui-surface-secondary': '#5e44db',
      '--ui-surface-hover': '#f7fafc',
      '--ui-border-default': '#e2e8f0',
      '--ui-border-subtle': '#eeeeee',
      '--ui-border-strong': '#cbd5e0',
      '--ui-status-success': '#22c55e',
      '--ui-status-warning': '#f59e0b',
      '--ui-status-info': '#3b82f6',
      '--ui-status-danger': '#ef4444',
      '--table-header-bg': '#5e44db',
      '--table-header-text': '#ffffff',
      '--table-header-border': '#5e44db',
      '--table-header-hover-bg': '#7b61ff',
      '--table-body-bg': '#ffffff',
      '--table-row-bg': 'transparent',
      '--table-row-hover-bg': '#f3f0ff',
      '--table-row-selected-bg': '#5e44db',
      '--table-row-border': '#eeeeee',
      '--table-cell-text': '#1a202c',
      '--table-empty-text': '#4a5568',
      '--table-loading-text': '#4a5568',
    }
  },
  {
    id: 'orange',
    name: 'Orange',
    primaryColor: '#ff9f1c',
    tokens: {
      '--ui-interaction-primary': '#ff9f1c',
      '--ui-interaction-primary-hover': '#ed8f0f',
      '--ui-interaction-primary-selected': '#d98009',
      '--ui-interaction-primary-selected-hover': '#c57308',
      '--ui-interaction-primary-selected-active': '#b16607',
      '--ui-interaction-success': '#22c55e',
      '--ui-interaction-success-hover': '#16a34a',
      '--ui-text-on-primary': '#ffffff',
      '--ui-text-on-primary-selected': '#ffffff',
      '--ui-text-on-success': '#ffffff',
      '--ui-text-on-secondary': '#ff9f1c',
      '--ui-text-on-tertiary': '#ff9f1c',
      '--ui-text-secondary': '#4a5568',
      '--ui-text-tertiary': '#718096',
      '--ui-text-placeholder': '#a0aec0',
      '--ui-surface-primary': '#ffffff',
      '--ui-surface-secondary': '#d98009',
      '--ui-surface-hover': '#f7fafc',
      '--ui-border-default': '#e2e8f0',
      '--ui-border-subtle': '#eeeeee',
      '--ui-border-strong': '#cbd5e0',
      '--ui-status-success': '#22c55e',
      '--ui-status-warning': '#f59e0b',
      '--ui-status-info': '#3b82f6',
      '--ui-status-danger': '#ef4444',
      '--table-header-bg': '#d98009',
      '--table-header-text': '#ffffff',
      '--table-header-border': '#d98009',
      '--table-header-hover-bg': '#ff9f1c',
      '--table-body-bg': '#ffffff',
      '--table-row-bg': 'transparent',
      '--table-row-hover-bg': '#fff5e6',
      '--table-row-selected-bg': '#d98009',
      '--table-row-border': '#eeeeee',
      '--table-cell-text': '#1a202c',
      '--table-empty-text': '#4a5568',
      '--table-loading-text': '#4a5568',
    }
  },
];

export function getDefaultTheme() {
  return themes[2]; // blue
}
